### ISSUE TITLE
Expected a value of type 'List<int>', but got one of type 'Null' (excel.encode())

### ISSUE THREAD

**Issue by MoonshotPioneerTom** [justkawal/excel#138]

**Comment by MoonshotPioneerTom** [comment]
Please help , thanks..

**Comment by bhanuka96** [comment]
This plugin looks like outdated. Use this [plugin](https://pub.dev/packages/syncfusion_flutter_xlsio)

**Comment by regalmojo** [comment]
same issue

**Comment by chuyentt** [comment]
Try this:
```yaml
  excel:
    git:
      url: https://github.com/justkawal/excel.git
      ref: null-safety
```
