### ISSUE TITLE
Renaming a sheet makes excel crash in print preview

### ISSUE THREAD

**Issue by mockfrog** [justkawal/excel#58]
Hi @justkawal, thanks for this really helpful plugin, but I have a issue with it.

I create a new excel file, rename the first sheet and save it.
When I open it in excel it shows up correctly, but when trying to print it, excel just crashes.

Here is a small code snippet to demonstrate the problem I have:

**pubspec.yaml**
```yaml
name: exceltest
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  path: ^1.7.0

  excel: ^1.1.5

dev_dependencies:
  pedantic: ^1.9.0
```

**main.dart**
```dart
import 'dart:io';
import 'package:excel/excel.dart';
import 'package:path/path.dart';

void main(List<String> arguments) {
  var excel = Excel.createExcel();
  excel.rename(excel.tables.keys.first, 'NewName');
  excel.encode().then((onValue) {
    File(join('./excel.xlsx'))
      ..createSync(recursive: true)
      ..writeAsBytesSync(onValue);
  });
}
```
